import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import StarsCanvas from "@/components/StarBackground";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gabryel Willers Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} bg-[#030014] overflow-y-scrool overflow-x-hidden`}><StarsCanvas/>{children}</body>
    </html>
  );
}
